# Generated by Django 4.0.1 on 2022-01-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='postF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.featured'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
