# Generated by Django 4.0.1 on 2022-01-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_postf_alter_blogcomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='postF',
        ),
    ]
