# Generated by Django 4.0.1 on 2022-02-10 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_toppost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
